<a href="https://colab.research.google.com/github/sakshammverma/ML_Algorithms/blob/main/MultipleLR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

In [71]:
X,y=load_diabetes(return_X_y=True)

In [72]:
X.shape

(442, 10)

In [73]:
y.shape

(442,)

In [74]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [75]:
class MLr:
  def __init__(self):
    self.coef=None
    self.intercept=None

  def fit(self,X_train,y_train):
    X_train= np.insert(X_train,0,1,axis=1)
    #betas are coefficients
    betas=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    self.intercept=betas[0]
    self.coef=betas[1:]

  def predict(self,X_test):
    y_pred=np.dot(X_test,self.coef)+self.intercept
    return y_pred


In [76]:
np.insert(X_train,0,1,axis=1)

array([[ 1.        , -0.00188202, -0.04464164, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [ 1.        , -0.00914709, -0.04464164, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 1.        ,  0.02354575,  0.05068012, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 1.        ,  0.06350368,  0.05068012, ..., -0.00259226,
         0.08449153, -0.01764613],
       [ 1.        , -0.05273755,  0.05068012, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 1.        ,  0.00175052,  0.05068012, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [77]:
lr=MLr()

In [78]:
lr.fit(X_train,y_train)

In [79]:
y_pred=lr.predict(X_test)

In [80]:
lr.intercept

151.88331005254165

In [81]:
lr.coef

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [82]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.43993386615689634



---

**MULTIPLE LINEAR REGRESSION FROM SKLEARN**

In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
mod=LinearRegression()

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [40]:
mod.fit(X_train,y_train)

LinearRegression()

In [41]:
y_pred=mod.predict(X_test)

In [42]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4399338661568968

In [44]:
mod.intercept_

151.88331005254167

In [46]:
mod.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])